spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
---
spring:
  profiles: zuul1
zuul:
  ignoredServices: microservice-consumer-movie-ribbon-with-hystrix
  routes:
    microservice-provider-user: /user/**
---
spring:
  profiles: zuul2
zuul:
  routes:
    users: #g该项只需唯一就行，不影响访问路径
      path: /user/** #**表示匹配多级
      serviceId: microservice-provider-user
---
spring:
  profiles:zull3
zuul:
  routes:
    users:
      path: /user/**
      serviceId: microservice-provider-user
ribbon:
  eureka:
    enabled: false
microservice-provider-user:
  ribbon:
    listOfServers: http://localhost:7900,http://localhost:7901
---
spring:
  profiles: zuul4
