spring:
  application:
    name: microservice-hystrix-turbine
server:
  port: 8032
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
    instance:
      prefer-ip-address: true

turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie-feign-hystrix-fallback-factory,microservice-consumer-movie-ribbon-hystrix
  clusterNameExpression: "'default'"

#turbine:
  #aggregator:
    #clusterConfig: MICROSERVICE-CONSUMER-MOVIE-FEIGN-HYSTRIX-FALLBACK-FACTORY,MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX
  #appConfig: microservice-consumer-movie-feign-hystrix-fallback-factory,microservice-consumer-movie-ribbon-hystrix
